spring.application.name=SystemMonitor
server.port=8045

# PostgreSQL Configuration (Users, Computers, Specs)
spring.datasource.url=jdbc:postgresql://localhost:5432/system_monitor
spring.datasource.username=monitor
spring.datasource.password=redfox21
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# InfluxDB Configuration (Metrics)
influxdb.url=http://localhost:8086
influxdb.token=monitor-token-21170351
influxdb.org=system-monitor
influxdb.bucket=metrics
management.metrics.export.influx.api-version=v2

# JWT Configuration (For Mobile App Auth)
app.jwtSecret=SecretKeyGenJWTEnumKeyMustBeLongEnoughForSecurity123456
app.jwtExpirationMs=86400000